project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "reviews/*.qmd"
    - "!review-template.qmd"

execute:
  freeze: false

website:
  title: "Review Articles"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - about.qmd
      - section: "All Reviews"
        contents: "reviews/*.qmd"


format:
  html:
    theme: cosmo
    toc: false
    grid:
      sidebar-width: 300px
      body-width: 1100px
      gutter-width: 1.5rem
    css: styles.css